name: Codespell
on: [pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: codespell
        uses: codespell-project/actions-codespell@master
        with:
          # only show the typo detected but don't make workflow to fail
          only_warn: 1
          skip: "*.ts"
          ignore_words_list: ba,DOUT,WEL
